### ISSUE TITLE
Were is the napalm REEEEEEEEEEEEEEE

### ISSUE THREAD

**Issue by BubbaFrog** [N-nec/enemy#1]
were's the napalm !!! its a vietnam mod

**Comment by N-nec** [comment]
This Mod is not in any reference to any race, religion or history/war.

The Models are Gender-less, if you perceive an authority as a male figure then these are male soldiers to you .


Does the Dog need updated?

**Comment by BubbaFrog** [comment]
https://www.youtube.com/watch?v=N7qkQewyubs

**Comment by N-nec** [comment]
Its a Mod to provide Shooting Enemies.

I updated the models to make it more realistic.

**Comment by BubbaFrog** [comment]
![th-933206062](https://user-images.githubusercontent.com/100529581/217992300-19c76579-e49e-4c10-b741-82757de9e2b6.jpeg)

**Comment by N-nec** [comment]
![aaaaaaaa](https://user-images.githubusercontent.com/95116319/217992596-91755ea4-ddad-423e-a7df-913fe8e2edad.gif)

**Comment by BubbaFrog** [comment]
me when I am playing with the mod

![pepe-reee-182782836](https://user-images.githubusercontent.com/100529581/217992764-712078c5-a6ac-41b1-b8ac-f2d46eed9a91.gif)

**Comment by N-nec** [comment]
Hahahahaha


![5ad090e05d331d907a2077118c3c9556](https://user-images.githubusercontent.com/95116319/217993145-ed238392-bfb1-4ede-8b9c-674e6db55913.jpg)
